### ISSUE TITLE
Last Stand denying armour protection

### ISSUE THREAD

**Issue by kientuong114** [OpenMods/OpenBlocks#555]
Sometimes when wearing a Last Stand II armour (Doesn't need to be on all pieces), if you receive damage, it bypasses armour and leaves you with only 0.5 hearts left.
This only works if the sword deals a damage greater or equal than 9 hearts (e.g. Diamond Sword w/ Sharpness IX (By cheating) or modded swords that deal greater damage).
Tested on both vanilla and modded armours and swords.
Tested using Modsauce Modpack version 1.0.0.5 with OpenBlocks version 1.7.10-1.3-snapshot-435 modlist : http://hermitcraft.com/modsauce

**Comment by symmetry93** [comment]
This does not seem to be fixed in OpenBlocks 1.5.1. I have set up a test world with only OpenBlocks and I do take more damage than I should when I have insufficient health left. It happens without excessively high damage received, it just has to be enough to kill you if you're not wearing armour. E.g: Zombie with diamond sword, player has diamond armour with Last Stand. Normally should take one heart per hit, but at 5 hearts remaining, player loses 4.5 hearts and starts losing XP.

It also happens reliably, so it's not a rare occurrence. Forge version is the latest for 1.7.10, 10.13.4.1614.

**Comment by boq** [comment]
Hmm, looks like it has always used invalid damage (pre- armor and potions). Should be fixed now.
