### ISSUE TITLE
Server crash when using OpenBlocks/OpenModsLib on Forge server

### ISSUE THREAD

**Issue by thormbush42** [OpenMods/OpenBlocks#604]
I am currently experiencing an issue that, as far as I can tell from the lack of Google results, is a fairly recent problem. Basically, what happens is whenever I - or anyone else for that matter - tries to join the modded server, the server crashes. I have tried joining the server without these mods loaded on the server - I could join without the server crashing - and I have tested with only these two mods loaded - the server crashed when trying to join. The link to the crash report and the forge log is shown below

Crash Report: http://pastebin.com/FLpMzDsW
Forge Log: http://pastebin.com/u8pBYwpu

Minecraft 1.7.10; OpenBlocks 1.3; OpenModsLib 0.6

**Comment by boq** [comment]
Known issue (and already fixed): Cauldron uses ASM4, I accidentally used ASM5 stuff (it worked, since that's the one Forge uses for quite some time).

You can probably safely replace OpenModsLib version with [this](http://www.openmods.info:8080/job/OpenModsLib/285/artifact/build/libs/OpenModsLib-1.7.10-0.6-snapshot-285.jar).
