### ISSUE TITLE
liquids held back by sponge keep trying to move toward the sponge

### ISSUE THREAD

**Issue by Zedrimar** [OpenMods/OpenBlocks#614]
so when I place a sponge to remove liquids, instead of the liquids staying put, they try to flow towards the sponge and then get removed. maybe have the blocks update only after the sponge is removed?

**Comment by ajloveslily14** [comment]
Why is this a problem? It's how vanilla ones work.

**Comment by Ianaver** [comment]
it can cause lag and looks REALLY weird :/

**Comment by Ianaver** [comment]
maybe if there was a "Soaked" or "Wet" sponge then this mechanic would make more sense.

**Comment by nevercast** [comment]
I do believe this block used to not cause block updates. This has changed and blocks are notified so water moves again. The issue is that without a block notify you either have to notify all the blocks to update when the sponge is removed or you get gaps in water that stay there when removing the block. 

Though it's originally implementation I'm not certain of any implementation that differs from the current one also have a lot of pitfalls. I'm not sure to mark this as bug or intended operation so I'll leave it as an enhancement suggestion.

**Comment by nevercast** [comment]
Further thought I think that the best implementation beyond the current one would be to do a block update after the sponge is removed but only to update any liquid type block, and making sure that no neighbours are updated. This is probably the best method.

I'll experiment with this later if no one else does before me.

**Comment by Ianaver** [comment]
@nevercast  ok thx! :D

**Comment by Ianaver** [comment]
@nevercast also I think that its a good idea to at least start experimenting on a forked version since this issue has been posted for quite some time and it would be nice to finally maybe find a workaround!

**Comment by Ianaver** [comment]
@nevercast try making the sponge update all blocks in the radius of where liquids are held back, when it is removed. That may work...

**Comment by Ianaver** [comment]
@nevercast proposed solutions: 
a) make there be a soaked/wet sponge and remove the timer for liquid removal
b) send block update in a radius of area affected +1 (or two) only when the block is removed and get rid of the timer for liquid removal

**Comment by boq** [comment]
Hello from dystopian future of almost 2018!

I don't remember why block update was introduced (porting problems?), so I just implemented option b), since:
- it improves performance (#867)
- it's more derpy and possibly OP -> more fun.
