### ISSUE TITLE
Hardcore Ender Dragon breaks OpenBlocks graves.

### ISSUE THREAD

**Issue by border999** [OpenMods/OpenBlocks#673]
I fought the dragon, died, came back, and the grave was broke.

**Comment by boq** [comment]
Seems like other mod is ignoring Forge hooks: [graves are already protected against vanilla dragon](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/block/BlockGrave.java#L36). I can't do anything more, since problem is [here](https://github.com/chylex/Hardcore-Ender-Expansion/blob/master/src/main/java/chylex/hee/entity/boss/EntityBossDragon.java#L615)

**Comment by border999** [comment]
Question, would turning off mobgriefing allow the grave to survive the dragon?

**Comment by boq** [comment]
Looks like HEE code implements this check, so it should work.

**Comment by border999** [comment]
thanks for the tip, not telling my brother though. Been bugging me like crazy about going to kill the dragon.
