### ISSUE TITLE
Luggage

### ISSUE THREAD

**Issue by linuxcodefire** [OpenMods/OpenBlocks#683]
When i hover over Luggage it says sitting false... how do i make it true?

**Comment by boq** [comment]
Where it says it's sitting? Any screenshot?

**Comment by TheSilkMiner** [comment]
I think you mean this.
![2015-08-05_10 54 52](https://cloud.githubusercontent.com/assets/11136677/9082226/e1e88f76-3b62-11e5-8555-c0e7e9379cbe.png)
This is "caused" by the mod WAWLA, an extension of Waila.
I am pretty sure this is because `EntityLuggage` extends `EntityTameable`.

**Comment by linuxcodefire** [comment]
yes

**Comment by TheSilkMiner** [comment]
As i thought, the mod responsible for this is WAWLA, and, more specificly [these lines of code](https://github.com/Darkhax-Minecraft/WAWLA/blob/master/src/main/java/net/darkhax/wawla/addons/generic/AddonGenericEntities.java#L73-L78).
I think the only way to do this on OpenBlock's end is by adding a check to the first `if` statement using ASM.
A possible edit could be
```java
 if (entity instanceof EntityTameable && cfg.getConfig(CONFIG_PET_SITTING) && !(entity instanceof openblocks.common.entity.EntityLuggage)) {
```
where `&& !(entity instanceof openblocks.common.entity.EntityLuggage) ` is the added part.

To answer to the OP question, at the moment there is no way to change the value of that line, because (long code digression starts) usually on `EntityTameable`s the `interact` method (which is called when a player right-clicks the entity) sets the sitting state of the entity, toggling it, like here:
```java
this.aiSit.setSitting(!this.isSitting());
```
This "functionality" is overridden in `EntityLuggage` to allow you to open his inventory on right-click and to pick it up on shift-right-click ([code viewable here](https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/common/entity/EntityLuggage.java#L118-L139)).
(end of long code digression)

**Comment by boq** [comment]
Thank you for extensive explanation!

Anyway, my response: I'm not fixing that, since "sitting" does not make any sense for luggage right now.

**Comment by Talavar** [comment]
SItting would be very nice.. I have two chests.. One is a tool box that carries my quarry, wrenches, pipes, etc, etc.. Named "Tool box" obviously.. however I don't need it following me around all the time, I'd like to be able to make it "sit" at my base so its not filling itself up with random junk while im out and about. I could shift-rightclick and throw it in a chest, I know.. But a sit function would be much "cooler" ;)
