### ISSUE TITLE
Graves does not appear in OpenBlocks 1.4.3

### ISSUE THREAD

**Issue by retrozool** [OpenMods/OpenBlocks#691]
Not sure whether it's the right place to ask but I basically tried everything to make graves work and don't succeed.
I'm using the unmodified FTB modpack "Cloud 9" v1.1.1 (which is using OpenBlocks 1.4.3)
Graves enabled in config (as well as the extended debug)
Once I die the *death-0.dat files is created but still items drop, no grave.
Is there any mod conflicting the creation of the grave?

The only server log file output on death is:

[17:51:39] [Server thread/INFO] [OpenMods/]: openblocks.common.PlayerInventoryStore.onPlayerDeath(PlayerInventoryStore.java:303): Storing post-mortem inventory into /games/ni4/ftproot/minecraftftb/./worldNT/data/inventory-TZ-2015-08-17_17.51.39-death-0.dat. It can be restored with command '/ob_inventory restore TZ TZ-2015-08-17_17.51.39-death-0'

**Comment by bdudek** [comment]
i can say this its Advent of Ascension i have had the same problem and in testing i removed advent and i had graves again idk what caused this but for my server we just play with keep inventories on now

**Comment by nevercast** [comment]
The onPlayerDrops event does the Grave spawning, even when the event is cancelled.
In the case of another mod, they listen to the LivingDeath event: 
https://github.com/NightKosh/GraveStone-mod/blob/master/src/main/java/gravestone/core/event/GSEventsHandler.java#L39

However this doesn't mitigate the issue, shown here:
https://github.com/NightKosh/GraveStone-mod/issues/191

The problem seems to be that Advent of Ascension is 'muting' the PlayerDrops event and removing the inventory preventing other events doing the same action. 

It's pointless for these mods to fight about which "action" is the right one in the event of player death, since both OpenBlocks and AoA have different intensions about your inventory at time of death.

Options are:
* If AoA provides a way to disable it's drops/skill system, use that. 
* If it does not and you prefer to keep your inventory, set keep inventories as a gamerule
* Alternatively remove or disable AoA to get Graves back.

I will investigate other options, but for the most part the result you want is an incompatibility. AoA is designed to prevent all Grave mods from working until you have enough 'Augury' skill.

**Comment by boq** [comment]
Please read answer to `Grave didn't spawn/Some items are missing?` in our [FAQ](http://openmods.info/faq.html)

**Comment by retrozool** [comment]
Yeah I tried everything mentioned in the FAQ - still no output and not working at all.
It seems that it is really related to AoA and the only way to get graves is to disable AoA (which is a bummer!)
Asked the author of AoA whether he's planning to make the whole Augury skill configurable to add compatibility to OpenBlocks graves (still no answer)

**Comment by boq** [comment]
Our general policy is "Should work, but if it doesn't, you are on your own, since it's not supported environment". Here are some hints about debugging graves: https://openmods.info/faq.html#ob-0.

And please don't post in old, closed issues.

**Comment by TomTheHero** [comment]
So you will not support the only up to date thing that can run both mods and plugins at once

**Comment by boq** [comment]
It doesn't matter what it does support, only what it breaks or doesn't support. Making changes platform-specific changes would made it incompatible with common baseline.

Though it is probably mod interaction, as usually. I strongly suggest following troubleshooting procedure I posted. If it doesn't work with just OpenBlocks in flat world, I suggest reporting to Sponge that their support entity drops is broken.

**Comment by TomTheHero** [comment]
They already told me it is completely fine when i had issues with it a month or 2 ago and they told the mod devs to fix their issues

**Comment by boq** [comment]
It would be nice to see that conversation. Anyway, `PlayerDropsEvent` probably works in spongeforge. And I know OpenBlocks works on its own, since I wouldn't release if it would.

As I said, it's probably mod interaction and I can't help you, since I don't know what combination of 21866+ existing mods you have installed. Again, troubleshooting section contains information how to list all interfering mods (`debug:gravesDebug` config).

**Comment by TomTheHero** [comment]
It turns out that the grave does actually exist but invisible and invulnerable, a block must be put into it's position and broken in order for the 'grave' to actually break.
And here is the debug: https://pastebin.com/BtbD7eSQ

**Comment by boq** [comment]
That's sounds like server is not sending block updates to client. It will probably show after you click F3+A or re-log.

**Comment by TomTheHero** [comment]
Already tried that, it doesn't

**Comment by boq** [comment]
Then I have no idea what's wrong. Block is in world, works as expected (since breaking logs correctly), yet server does not send it to client as it should with just Forge. Grief prevention maybe?

**Comment by TomTheHero** [comment]
I only use a factions plugin to protect spawn a little bit as griefprevention and universeguard work awfully on sponge

**Comment by TomTheHero** [comment]
I just tried without any plugins and it still occured, then i removed spongeforge and everything worked

**Comment by nevercast** [comment]
If you've tried with only OpenBlocks and SpongeForge, with no other mods and no other plugins. Then it's a SpongeForge issue, please raise the issue with them. Closing this discussion because this is grave digging, ironically.
