### ISSUE TITLE
[Enhancement] Conversion between Liquid XP and MFR Essence

### ISSUE THREAD

**Issue by mikeloeven** [OpenMods/OpenBlocks#717]
Considering the identical nature of the two liquids please add Ore Dictionary support for MFR Essence as Liquid XP

**Comment by boq** [comment]
- as far as I know there is no Ore Dictionary for liquids. Forge system allows to use only one of alternatives at the time
- they are rather different
- we discussed adding interchangeability some time ago and decided against it, mostly due to incompatible ratios

Right now only way to exchange is via XP orbs (shower + grate) or player levels (right click on tank + grate)
