### ISSUE TITLE
1.8 Support

### ISSUE THREAD

**Issue by Gaelan** [OpenMods/OpenBlocks#728]
MC 1.7.10 is 2 years old, and 1.9 is almost around the corner. I say it's time we get to work on a 1.8 port. What do you guys think?

**Comment by Spartan322** [comment]
You do understand what that entails right?

**Comment by Gaelan** [comment]
I understand that it will be a lot of work, if that is what you mean. I just figured that I should get the ball rolling.

**Comment by SinZ163** [comment]
raising an issue on it isn't really getting the ball rolling, and its probably not happening.


>\<Cricket> So have you started on 1.8?
\<boq> nope. changes in 1.8.8 look interesting, but I'm still not convinced it's worth to port instead of working on new features
\<Cricket> I hear ya there
\<boq> really, forge people did a great job on 1.8.8 (generics, renaming, etc), but it still has some technical problems. But 1.9 looks even better, based on stuff I hear from mojang guys
\<Cricket> I have talked to Searge about 1.9. I am really excited

**Comment by Gaelan** [comment]
Interesting. I personally think we should move to 1.8 first, just because the modding community is generally quite slow with regards to upgrades. It would be a shame to be stuck on 1.7.10 for another year+. Anyway, not my decision to make.

**Comment by Spartan322** [comment]
The biggest issue is that model system, it was just shoved down our throats, that along side the model layer system (which, while arguably better for management, really breaks more intricate mods), makes implementing 1.8 highly difficult. 90% of the conversion is practically equivalent to erasing and rewriting.

**Comment by Gaelan** [comment]
Does 1.9 change this again and/or make it much easier?

**Comment by boq** [comment]
Just to clarify, when I was talking about "technical problems", I meant 1.8.8 only. 1.8 is mature and usable. Also, "technical problems" include stuff like "sometimes explodes", but not any of the architectural decisions.

I think models, removal of ISRBH, blockpos etc. are changes in right direction. but aligning to those changes require quite a lot of work, so I decided to delay it until some vanilla internals are more polished (1.9) and not frozen in middle of transitioning from notchcode to something more extendable. Though I might revise this decision, since 1.9 was delayed.
