### ISSUE TITLE
Elevator, Better Sprinting interaction

### ISSUE THREAD

**Issue by zxexuxs** [OpenMods/OpenBlocks#753]
Im Playing FTB:IE and noticed the elevator ist working, but since no one reported this issue i thought it may be caused by better sprinting and indeed it is.
I dont know what exactly is changed by the mod but probably is messes around with the sneak key which triggers the elevator. interestingly, jumping wont work, too.

In short:
Elevator doesnt work when better sprinting is installed(Neither sneaking nor jumping trigger the elevator)

**Comment by boq** [comment]
Ooooh, nasty way of implementing it. Anyway, nothing I can do on my side. Fortunately, OpenBlocks has fallback mechanism.

Open `OpenModsLibCore.json` in config folder on client, find `activate_movement_callback` and change line below it from `"value": "true"` to `"value": "false"`.

Or just add PlayerAPI, since it also causes OpenBlocks to use fallback.

**Comment by zxexuxs** [comment]
It works fine now (I used the first possibility)
Thanks for your help.

**Comment by mcdodge34** [comment]
Ok, just installed Openblocks in 1.12.2 and noticed the OpenModsLibCore.json doesn't have any option for movement callback, since there's no playerapi out for this version, I'm pretty much stuck with elevators that don't work, the ones from ElevatorMod works fine. I'm unsure if I should open a new issue here or this one will get your attention,,,

**Comment by boq** [comment]
For 1.12 it's #882 duplicate.

Report it to Better Sprinting, since it's their coremod that breaks hook supplied by Forge.

**Comment by mcdodge34** [comment]
Ok then, will use the Elevator mod since it does work and will simply hope that Better Sprinting will fix this, but this problem exist for so long that I don't expect them to fix it anytime soon, 2 yrs later and they didn't change their method.

**Comment by boq** [comment]
Well, in 1.7.10 it was "use third-party hook lib, which interferes with other hook", but in 1.12 it's "use homebrew coremod to break Forge functionality", so it changed from compatibility issue to rather obvious bug.

**Comment by mcdodge34** [comment]
I don't understand this kind of things, just reporting what I get to help devs whenever I can, for now, I use a ported version of the Elevator and I simply disabled the one from OpenBlocks in config so it wouldn't overlap since recipe is the same, just miss the rotating elevators but I can live without them. I'll check configs of Better Sprinting, maybe they added some fix, been awhile since I checked their config files (if they have any)

**Comment by chylex** [comment]
To clarify, ever since Better Sprinting (BSM) became a Forge mod, it *always* replaced either the entire `EntityPlayerSP` class, or the entire `onLivingUpdate` chain from `EntityPlayerSP` to `Entity`.

That was also the case with a PlayerAPI fallback, which was made to improve compatibility, but would remain incompatible with any mod that changed `onLivingUpdate`.

The homebrew coremod was made around 1.12 after I got tired of a long update process, and now BSM only replaces about 2/3 of `onLivingUpdate` instead of the whole chain, which is more compatible and has way fewer bugs than anything before it.

The issue in 1.12.2 is happening because BSM for that version came out over a month *before* Forge added the hook OpenBlocks uses, and I was only notified of the issue today.

**Comment by boq** [comment]
Thank you for fixing that!

(For future reference: https://github.com/chylex/Better-Sprinting/issues/32)
