### ISSUE TITLE
[Question] Hang Glider ThermalLift beep/tone

### ISSUE THREAD

**Issue by gravitystix** [OpenMods/OpenBlocks#821]
Hi there, just created this account to ask about the noise the hang glider makes when in flight. From what I gather reading around here the tone it makes is intentional? I'm just confused because it sounds like I'm tuning a short wave radio, not gliding through the air. It's just a sine wave changing frequency between somewhere around 500 and 600hz.

If this is intentional and not a bug, might I suggest changing it to some sort of variable white noise whoosh so it sounds a little more like wind? I'm using OpenBlocks in the SpaceAstronomy pack on FTB if that makes a difference. 

Also if there's a way to disable the sound for the glider in the meantime please let me know! Love your mod, keep up the great work.

**Comment by emmertf** [comment]
Hi, that tone is intentional - what you are hearing is an acoustic variometer (https://en.wikipedia.org/wiki/Variometer). It indicates vertical air movement. Vertical air movement happens naturally due to sun-heated air moving upwards (thermals). Higher tones mean you are sinking slower and a broken "beeping" tone indicates that you are gaining altitude. If you use it correctly you'll be able to extend your flight quite a bit.

If you don't want to hear it, you can disable the tone by pressing "V". You can also increase and decrease the volume, but you have to assign keys for that first (using the ingame keyboard layout settings).

**Comment by gravitystix** [comment]
Thanks for the quick response! I should've checked the keybinds, had something else mapped there. Never heard of an acoustic variometer before but that's fascinating! Little too much realism for me though. Thanks again.

**Comment by emmertf** [comment]
Well it's a fun way to enable long-distance gliding without overpowering the glider ;)
If you want, you can try flying in circles while the tone is broken/beeping - you can cross oceans that way. You'll have to experiment a little until you find the right altitude, also it doesn't work during nighttime or while it rains. Have fun!
