### ISSUE TITLE
[1.12]  When I placed two Sky blocks side by side the game crashes with GL Error

### ISSUE THREAD

**Issue by PrinceOfAmber** [OpenMods/OpenBlocks#860]
It just says "[17:14:21] [main/WARN]: GL Error in TileDrawStep: 1286" a whole ton of times

Looks like a Journeymap conflict?  

Pastebin below

https://pastebin.com/pmmY6yjv

**Comment by boq** [comment]
I'm unable to reproduce with just JourneyMap. Can you run command `/gl_debug medium` and post logs? After that, extra logs can be disabled with `/gl_debug disable`.

**Comment by dottiekh** [comment]
I'm fairly certain the error spam is caused simply by Optifine's presence along with the shaders enabled, rather than JourneyMap causing it. I was able to replicate this by enabling a shader pack using Optifine and placing the sky block. Screen completely froze and console was being spammed with the same error. Additionally even without a shader pack selected, the sky block render doesn't work at all. Disabling optifine resolves both of these afaik.

**Comment by boq** [comment]
Yup, seems like Optifine problem. Can't do anything, so here are details from my side, if you want to report it to them:

Tested with: preview_OptiFine_1.12.2_HD_U_C8_pre.jar
More detailed log: https://gist.github.com/boq/673bb70f1c1dc5bcf669fb3ad86ce06a
What OpenBlocks is doing with framebuffer: https://github.com/OpenMods/OpenBlocks/blob/master/src/main/java/openblocks/client/renderer/SkyBlockRenderer.java#L60

**Comment by boq** [comment]
Skyblock will no longer render on default when Optifine is disabled. I guess this closes this issue (somehow).
