### ISSUE TITLE
1.12.2 Block Breaker not outputting to transport pipes.

### ISSUE THREAD

**Issue by MarshTheBacca** [OpenMods/OpenBlocks#868]
I use the block breaker in a cobblestone generator for my ME system cobble supply. I tried attaching Mekanism's basic logistical transporters to the correct output side (opposite to the breaking side), and yet the blocks aren't being fed into the transporter. I tried using BuildCraft's golden transport pipes too but the didn't work either, however both pipes do show a graphical attachment to the block breaker.

Thanks for any help and I hope it gets fixed :)

**Comment by MarshTheBacca** [comment]
I noticed there has to be an output to a chest for it to work, but in the block description it says it can be fed directly into pipes.

**Comment by boq** [comment]
On baseline, we work with anything that looks like vanilla inventory (i.e. chest), so buffer chest will indeed work.

Before 1.10 we provided support for BC pipes, which was removed since there are no stable builds (once they show up I will consider adding it). As for Mekanism - I don't see usable API, so looks like skip for now.
