### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by MasonBlood9696** [OpenMods/OpenBlocks#989]
I have a mod that can tell me the cause of the game crash. It says it was Applied Energistics 2 fault. But it was't that mods fault. It has to do with OpenBlocks. 

Here is the full detail:
https://paste.dimdev.org/unevihorez.mccrash

Please help.

**Comment by boq** [comment]
It's not related to OpenBlocks, trophy block (which has no AE2 interactions) just happens to be where AE2 expects controller. I suggest getting back to https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4200, since it seems like same issue (which might be world corruption due to some third party mod).
